name: petmeals
description: App para los amantes de las mascotas
publish_to: none
version: 0.2.1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.19.0
    cloud_firestore: ^4.9.1
    firebase_auth: ^4.9.0
    firebase_core: ^2.15.1
    firebase_storage: ^11.2.7
    provider: ^3.2.0
    get_it: ^3.0.3
    cached_network_image: ^3.2.3
    day_night_time_picker: ^1.3.0+1
    easy_mask: ^2.0.1
    equatable: ^1.0.1
    flutter_dotenv: ^5.1.0
    flutter_image_compress: ^2.3.0
    path: ^1.9.0
    flutter_svg: ^2.0.7
    get_storage: ^2.1.1
    google_fonts: 6.1.0
    google_mobile_ads: ^5.1.0
    go_router: ^11.1.2
    google_sign_in: ^6.1.5
    image_picker: ^1.0.4
    logger: ^0.7.0+2
    lottie: ^3.0.0
    time_parser: ^1.2.1
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^2.0.3
flutter_launcher_icons:
    android: launcher_icon
    ios: true
    image_path: assets/logo/pet.png
    adaptive_icon_background: assets/logo/pet.png
flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/images/
        - assets/logo/
        - assets/images/icons_att/
        - assets/images/icons/
        - .env
        - .env.dev


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages