name: comfypet
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #** core
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.7
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  #** dependencias
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  flutter_svg: ^2.0.7
  animate_do: ^3.1.2
  get_storage: ^2.1.1
  go_router: ^11.1.2
  #** manejadores
  #* get_it
  get_it: ^7.6.4
  get_it_mixin: ^4.2.2
  #* provider
  # provider: ^6.0.5
  #* cubit bloc
  # flutter_bloc: ^8.1.3
  # bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_app.png"
  adaptive_icon_background: "assets/logo/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/icono/
    - assets/images/icons/
    - json/
