name: petmeals
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #** core
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.7
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  #** dependencias
  animate_do: ^3.1.2
  cached_network_image: ^3.2.3
  easy_mask: ^2.0.1
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  go_router: ^11.1.2
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  time_parser: ^1.2.1
  #** manejadores
  #* get_it
  get_it: ^7.6.4
  watch_it: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/pet.png"
  adaptive_icon_background: "assets/logo/pet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/icono/
    - assets/images/icons/
    - json/
