name: petmeals
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # cupertino_icons: ^1.0.8
  #
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.7
  google_mobile_ads: ^5.1.0
  # plugins
  # animate_do: ^3.1.2
  cached_network_image: ^3.2.3
  day_night_time_picker: ^1.3.0+1
  easy_mask: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  google_fonts: 6.1.0
  go_router: ^11.1.2
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^3.0.0
  time_parser: ^1.2.1
  # manejadores
  provider: ^6.0.5
  get_it: ^7.6.4
  # equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/pet.png"
  adaptive_icon_background: "assets/logo/pet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logo/
    - assets/images/icons_att/
    - assets/images/icons/
    - .env
    - .env.dev
